In [5]:
import numpy as np
np_tesst = [0.1, 0, 1, 2, 3, 4, 5,2, 2,3.3, 2, 2, 0.1]
np.linspace(0, 5, 6)

array([0., 1., 2., 3., 4., 5.])

In [6]:
np.digitize(np_tesst, np.linspace(0, 5, 6))

array([1, 1, 2, 3, 4, 5, 6, 3, 3, 4, 3, 3, 1])

In [1]:
import numpy as np
np.loadtxt("/u/ryotainagaki/Desktop/CompletenessSim.dat", dtype ='object')

ValueError: Wrong number of columns at line 6

In [5]:
np.array([np.ones(12)]).transpose()

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])